<<<<<<< HEAD
import type { Metadata } from "next"
import ThemeLoader from "./components/ThemeLoader"
import "./globals.css"

export const metadata: Metadata = {
  title: "Silverstone Companion",
  description: "Offline-ready British GP weekend companion",
  manifest: "/manifest.json",
  themeColor: "#07080d",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Silverstone",
  },
}

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeLoader from "./components/ThemeLoader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
>>>>>>> b7fdf86d610850e9c506c11bbbcc14d0596478e1
        <ThemeLoader />
        {children}
      </body>
    </html>
<<<<<<< HEAD
  )
}
=======
  );
}
>>>>>>> b7fdf86d610850e9c506c11bbbcc14d0596478e1
